export const data = [
  {
    id: 0,
    qty: 1,
    image: "/img1.png",
    price: "$200",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 1,
    qty: 1,
    image: "/img2.png",
    price: "$390",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 2,
    qty: 1,
    image: "/img3.png",
    price: "$1000",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 3,
    qty: 1,
    image: "/img4.png",
    price: "$790",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 4,
    qty: 1,
    image: "/img5.png",
    price: "$230",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 5,
    qty: 1,
    image: "/img6.png",
    price: "$100",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 6,
    qty: 1,
    image: "/img7.png",
    price: "$310",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 7,
    qty: 1,
    image: "/img8.png",
    price: "$810",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
  {
    id: 8,
    qty: 1,
    image: "/img9.png",
    price: "$230",
    title: "Ultraboost 5X Shoes",
    desc: "Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern personalized look.",
  },
];
